import { adminFetch } from "../../../lib/api";
import { SettingsForm, type FieldGroup } from "../../../components/SettingsForm";

const GROUPS: FieldGroup[] = [
  {
    title: "Company identity",
    description: "Used on every invoice header generated by the system.",
    fields: [
      { key: "invoice.company_name", label: "Legal company name", type: "text", defaultValue: "Eatofine Delivery Service Pvt. Ltd." },
      { key: "invoice.short_name", label: "Short brand name", type: "text", defaultValue: "EATOFINE" },
      { key: "invoice.tagline", label: "Tagline", type: "text", defaultValue: "Food Delivery Service" },
      { key: "invoice.logo_url", label: "Logo URL", type: "url", placeholder: "https://… or /storage/branding/invoice-logo.png" },
    ],
  },
  {
    title: "Registered office + statutory IDs",
    description: "Appears in the \"Eatofine Delivery Service Pvt. Ltd.\" block on every tax invoice.",
    fields: [
      { key: "invoice.registered_office", label: "Registered office address", type: "textarea", defaultValue: ". FF2, Vishnu Palace, Sec 20B, Faridabad NIT, Faridabad, Haryana, India, 121001, India" },
      { key: "invoice.state", label: "State", type: "text", defaultValue: "Haryana" },
      { key: "invoice.state_code", label: "State code", type: "text", defaultValue: "06", placeholder: "06" },
      { key: "invoice.cin", label: "CIN", type: "text", defaultValue: "U56103HR2025PTC131940" },
      { key: "invoice.gstin", label: "GSTIN", type: "text", defaultValue: "06ABCDE1234F1Z5" },
      { key: "invoice.pan", label: "PAN", type: "text", defaultValue: "ABCDE1234F" },
      { key: "invoice.fssai", label: "FSSAI ID", type: "text", defaultValue: "10024051234567" },
    ],
  },
  {
    title: "Contact",
    description: "Shown in the invoice footer.",
    fields: [
      { key: "invoice.email", label: "Contact email", type: "email", defaultValue: "eatofine@gmail.com" },
      { key: "invoice.website", label: "Website", type: "url", defaultValue: "www.eatofine.com" },
      { key: "invoice.support_phone", label: "Support phone", type: "text", placeholder: "+91 0000 000000" },
    ],
  },
  {
    title: "Layout",
    description: "Toggle what shows on the printed invoice.",
    fields: [
      { key: "invoice.show_tax_breakdown", label: "Show CGST + SGST split", type: "checkbox", defaultValue: "true", description: "Off = single combined GST line." },
      { key: "invoice.show_delivery_charge", label: "Show delivery charge", type: "checkbox", defaultValue: "true" },
      { key: "invoice.show_payment_status", label: "Show payment status badge", type: "checkbox", defaultValue: "true" },
      { key: "invoice.footer_note", label: "Footer note", type: "textarea", defaultValue: "This is a computer generated document. No signature required." },
    ],
  },
];

export default async function InvoiceSetupPage() {
  const data = await adminFetch<{ settings: Array<{ id: number; key: string; value: string | null }> }>(
    "/admin/business-settings?prefix=invoice.",
  );

  return (
    <div className="relative p-8 space-y-6 max-w-5xl">
      <div className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(circle_at_top,rgba(16,185,129,0.06),transparent_60%)]" />

      <div className="relative overflow-hidden rounded-2xl sidebar-gradient text-white shadow-xl shadow-emerald-900/30 ring-1 ring-white/10">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(110,231,183,0.45),transparent_55%)]" />
        <div className="relative px-8 py-7">
          <div className="flex items-center gap-2 text-xs uppercase tracking-[0.18em] text-white/70 font-semibold">
            <span className="inline-block w-1 h-1 rounded-full bg-white/70" /> SYSTEM · INVOICE
          </div>
          <h1 className="mt-2 text-3xl font-bold tracking-tight">Invoice Setup</h1>
          <p className="mt-2 text-sm text-white/80 leading-relaxed max-w-2xl">
            Customize what appears on every tax invoice generated by the platform — company details, registered office, GSTIN, footer text. Live-applies to new invoices instantly.
          </p>
        </div>
      </div>

      <SettingsForm initial={data.settings} groups={GROUPS} />
    </div>
  );
}
